main: net.connorcpu.plugjs.PlugJS
name: PlugJS
version: 1.0
description: Javascript environment for bukkit
commands:
  reloadjs:
    usage: /<command>
    description: Reloads the javascript environment (except persistence. add -p for that)
    permission: plugjs.reload